//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidadAireUtec.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheets
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string s_key { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
